// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXCiWmq-pG-Fnm6XJbfjKnJehit2BJD5A',
    appId: '1:54388432481:web:0227ae338a4c4782005420',
    messagingSenderId: '54388432481',
    projectId: 'kyorang-talk-3f8a0',
    authDomain: 'kyorang-talk-3f8a0.firebaseapp.com',
    storageBucket: 'kyorang-talk-3f8a0.firebasestorage.app',
    measurementId: 'G-M1DV9MF2ZE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCILXJLCBYlM507mka0JurMYL-1dWtKsAw',
    appId: '1:54388432481:android:535639fb76c45ef8005420',
    messagingSenderId: '54388432481',
    projectId: 'kyorang-talk-3f8a0',
    storageBucket: 'kyorang-talk-3f8a0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_CGUntG2vxe29g-O-Bvw4gL8XApP-xT8',
    appId: '1:54388432481:ios:9a6d38403c1d5e6e005420',
    messagingSenderId: '54388432481',
    projectId: 'kyorang-talk-3f8a0',
    storageBucket: 'kyorang-talk-3f8a0.firebasestorage.app',
    androidClientId: '54388432481-33nndtietu4jitbr0dumeo70ep6aplet.apps.googleusercontent.com',
    iosBundleId: 'com.kyorang.kyorangTalk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_CGUntG2vxe29g-O-Bvw4gL8XApP-xT8',
    appId: '1:54388432481:ios:9a6d38403c1d5e6e005420',
    messagingSenderId: '54388432481',
    projectId: 'kyorang-talk-3f8a0',
    storageBucket: 'kyorang-talk-3f8a0.firebasestorage.app',
    androidClientId: '54388432481-33nndtietu4jitbr0dumeo70ep6aplet.apps.googleusercontent.com',
    iosBundleId: 'com.kyorang.kyorangTalk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXCiWmq-pG-Fnm6XJbfjKnJehit2BJD5A',
    appId: '1:54388432481:web:b7ac8e823672e83d005420',
    messagingSenderId: '54388432481',
    projectId: 'kyorang-talk-3f8a0',
    authDomain: 'kyorang-talk-3f8a0.firebaseapp.com',
    storageBucket: 'kyorang-talk-3f8a0.firebasestorage.app',
    measurementId: 'G-FED7YWL4VB',
  );
}
